### ISSUE TITLE
Tuple unpacking in for loops

### ISSUE THREAD

**Issue by tBuLi** [HowToThink/HowToThink#14]
The book teaches tuple unpacking in for loops as 

``` python3
for (x, y) in pairs:
    pass
```

But the superfluous brackets are insane. It should be 

``` python3
for x, y in pairs:
    pass
```

Who is up for the regex challenge?

**Comment by pckroon** [comment]
`sed -re 's/for \(([a-zA-Z0-9_]+(, *[a-zA-Z0-9_]+)*)\) in ([a-zA-Z0-9_]+)\:/for \1 in \3\:/g'`

**Comment by pckroon** [comment]
Fixed in commit 5b895e7
