### ISSUE TITLE
The book on readthedocs

### ISSUE THREAD

**Issue by jbarnoud** [HowToThink/HowToThink#6]
We discussed yesterday about setting readthedocs to automatically build the book. I tried and it is trivial. Yet, I could only link readthedocs to my own fork of the book; only @tBuLi can link this fork to readthedocs. The steps to connect the fork are:
1. log in to read the doc
2. link your github account
3. import the repo
4. it is done

Here is the result on my fork: http://jon-think.readthedocs.org

And the pdf: http://readthedocs.org/projects/jon-think/downloads/pdf/latest/

**Comment by tBuLi** [comment]
I followed steps 1 and 2. However, when trying to import the repo I get redirected to your docs :(.

I could do a manual import of the repo, but maybe it's better if you unlink your fork from readthedocs?

**Comment by jbarnoud** [comment]
I also did a manual import. I just unlinked my version; both the one 
linked to my fork, and the one I did when trying to link to your fork. 
Tell me if it fix your issue.

**Comment by tBuLi** [comment]
Ok everything works perfectly now! The book is at howtothink.readthedocs.org, and I also double checked that we have a webhook active so it should autoupdate when we make changes here on github. I also updated the nestor page to reflect all this and removed the old books pdf.

So with that, I think we can close this issue.
